name: Deployment
on:
  workflow_dispatch:
    inputs:
      version:
        description: The current backend version, as set in the pom.xml
        required: true
jobs:
  build-client:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '12.x'
      - name: Build frontend
        run: |
          cd frontend
          npm ci
          npm run build
          cp -r dist/beescales/* ../backend/src/main/resources/public
      - name: Check backend
        run: |
          cd backend/src/main/resources/public
          ls
          pwd


#        ${{ github.event.inputs.logLevel }}