name: Deployment
on:
  workflow_dispatch:
    inputs:
      version:
        description: The current backend version, as set in the pom.xml
        default: 0.0.1-SNAPSHOT
        required: true
jobs:
  build-client:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '12.x'
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.2
        with:
          maven-version: 3.8.2
      - name: Build frontend
        run: |
          cd frontend
          npm ci
          npm run build
          cp -r dist/beescales/* ../backend/src/main/resources/public
      - name: Build backend
        run: |
          cd backend
          mvn clean install
          ls target
      - name: Upload jar on nextcloud
        uses: trympet/nextcloud-artifacts-action@v2
        with:
          name: 'beescales.jar'
          path: 'backend/target/beescales-${{ github.event.inputs.version }}.jar'
          nextcloud-url: 'https://cloud.bht-berlin.de'
          nextcloud-username: ${{ secrets.NEXTCLOUD_USERNAME }}
          nextcloud-password: ${{ secrets.NEXTCLOUD_PASSWORD }}